#!/bin/bash

# Expressão regular para validar a mensagem de commit
commit_pattern="^(Merge branch|Merged in|(feat|chore|fix|docs|style|refactor|perf|test|chore|build|ci|revert): .+)$"


# Ler a mensagem do commit
commit_message=$(cat "$1")

# Verificar se a mensagem de commit está no padrão
if [[ ! $commit_message =~ $commit_pattern ]]; then
    echo "A mensagem do commit não segue o padrão exigido!"
    echo "Use o padrão: tipo: mensagem informando o resumo do que foi feito"
    exit 1
fi

# Obtendo o nome do autor do commit
author_name=$(git config user.name)

exit 0