#!/bin/bash

# Padrão que desejamos verificar
branch_pattern="^(feature|hotfix|release|tests|docs)\/[a-z]+(-[a-z]+)*$"

# Obtendo o nome da branch atual
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Verificando se o nome da branch está de acordo com o padrão
if ! [[ "$branch_name" =~ $branch_pattern ]]; then
  echo "Erro: O nome da branch '$branch_name' não está no formato correto."
  echo "O nome deve estar no formato: 'prefixo/nome-minusculo-com-hifens'"
  echo "Prefixos permitidos: feature, hotfix, release, test, docs"
  exit 1
fi

exit 0